name: Test message

on:
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  notify-start:
    name: Notify release start
    uses: ./.github/workflows/notify-slack-start.yml
    secrets:
      slackToken: ${{ secrets.SLACK_BOT_RELEASE_TOKEN}}
    with:
      channel: 12gobiking-test
      message: Test
      notifyOnlyOnFailure: false

  release:
    runs-on: ubuntu-latest
    name: release
    steps:
      - name: sleep
        run: sleep 10s
        shell: bash

  notify-end:
    if: always()
    name: Notify release end
    needs: [ notify-start, release ]
    uses: ./.github/workflows/notify-slack-end.yml
    secrets:
      slackToken: ${{ secrets.SLACK_BOT_RELEASE_TOKEN}}
    with:
      time: ${{ needs.notify-start.outputs.time }}
      result: ${{ needs.release.result }}
      channel: 12gobiking-test
      message: Test
      notifyOnlyOnFailure: false
